HackerNewsViewer/config/routes.rb
HackerNewsViewer::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  get 'sort/comments'
  get 'sort/domain'

end

HackerNewsViewer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

HackerNewsViewer/app/controllers/sort_controller.rb
class SortController < ApplicationController

def comments
	#RAKE::TASK['sort_comments'].invoke
	call_rake :sort_comments
  	flash[:notice] = "sorting comments"
end

def domain
	#RAKE::TASK['domain'].invoke
	#call_rake :sort_domain
  	#flash[:notice] = "sorting domains"
end

#def headline_length
	#RAKE::TASK['headline_length'].invoke
	#call_rake :headline_length
  	#flash[:notice] = "sorting head-lines"
#end

end

HackerNewsViewer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

HackerNewsViewer/app/helpers/application_helper.rb
module ApplicationHelper
end

HackerNewsViewer/app/helpers/sort_helper.rb
module SortHelper
end

HackerNewsViewer/app/helpers/welcome_helper.rb
module WelcomeHelper
end

HackerNewsViewer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsViewer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

HackerNewsViewer/app/views/sort/comments.html.erb
<p>comments blah blah blah</p>

HackerNewsViewer/app/views/sort/domain.html.erb
<p>domain blah blah blah</p>

HackerNewsViewer/app/views/welcome/index.html.erb
<h1>Sorting Satates for Hacker News</h1>
<h4>Deep Local Interview Challenge for HSDouglas</h3>
<p>Sort news via:<ul>
	<li><%= link_to "number of comments", sort_comments_path %></li>
	<li><%= link_to "domain name", sort_domain_path %></li>
	<li>headline length (incomplete)</li>
</ul></p>